#include <stdio.h>
#include <netdb.h>

const char *pools[] = {
    "app-book",
    "app-cron",
    "app-emk",
    "app-intranet",
    "app-misc",
    "app-webapp",
    "av-intranet",
    "av-misc",
    "avkpi-misc",
    "bp-book",
    "bp-cron",
    "bp-emk",
    "bp-imggen",
    "bp-imggen-slow",
    "bp-intranet",
    "bp-intranet-slow",
    "bp-me",
    "bp-misc-slow",
    "bp-xml",
    "bp-xml-pci",
    "cs-misc",
    "csdata-cron",
    "csdata-misc",
    "dw-cron",
    "dw-cron-slow-SSD",
    "dw-intranet",
    "dw-intranet-slow-SSD",
    "dw-xml",
    "dw-xml-slow",
    "dwpreag-misc",
    "ed-misc",
    "emk-cron",
    "emk-misc",
    "events-cron",
    "events-misc-slow",
    "events-pool1",
    "events-pool2",
    "eventsavlog-cron",
    "eventsavlog-misc-slow",
    "eventsavlog-pool1",
    "eventsavlog-pool2",
    "eventstats-cron",
    "eventstats-misc",
    "eventstune-cron",
    "eventstune-misc-slow",
    "eventstune-pool1",
    "eventstune-pool2",
    "exp-cron",
    "exp-intranet",
    "fin-misc",
    "lkp-misc",
    "monitors-cron",
    "monitors-intranet",
    "monitors-misc",
    "monitors-webapp",
    "monitors-xml",
    "off-cron",
    "off-intranet",
    "off-misc",
    "off-misc-slow",
    "res-book",
    "res-cron",
    "res-cron-slow",
    "res-crypt",
    "res-favapp",
    "res-intranet",
    "res-intranet-slow",
    "res-mg",
    "res-misc",
    "res-misc-slow",
    "res-ppc",
    "res-statapp",
    "res-webapp",
    "res-xml",
    "res-xml-slow",
    "resarc-misc",
    "seo-misc",
    "srv-misc",
    "srv-xml",
    "stats-cron",
    "stats-fav",
    "stats-intranet",
    "stats-mg",
    "stats-misc",
    "stats-mz",
    "stats-seo",
    "sys-misc",
    "sysctl-misc",
    "user-book",
    "user-cron",
    "user-emk",
    "user-event",
    "user-intranet",
    "user-me",
    "user-webapp",
    "user-xml",
    "app",
    "av-office",
    "bp-csapp",
    "bp-csapp-slow",
    "csrdb",
    "dw-controlrooms",
    "dw-cron-slow",
    "dw-office",
    "dw-office-slow",
    "dwpreag",
    "ed",
    "emk-app",
    "emk-bp",
    "emk-user",
    "emkrdb",
    "events-slow",
    "eventsavlog-slow",
    "eventstune-slow",
    "exp-office",
    "lkp",
    "monitors-admin",
    "monitors-office",
    "off-app",
    "res-admin",
    "res-app",
    "res-cronapp",
    "res-cronapp-slow",
    "res-csapp",
    "res-csapp-slow",
    "res-office",
    "res-office-slow",
    "res-secure-admin:",
    "resarc",
    "seo",
    "stats-controlrooms",
    "stats-office",
    "sys",
    "sysctl",
    "user-app",
    "fv-apprdb",
    "fv-avrdb",
    "fv-bprdb"
};
const char domain[] = ".lb-pool";
const size_t poolsnr = sizeof(pools) / sizeof(*pools);

int main() {
	struct hostent *he;
	char pool[256];
	int last_addr = 0;
	int i;
	size_t dups = 0;

	for (i = 0; i < 100000; i++) {
		snprintf(pool, sizeof(pool), "%s%s", pools[i % poolsnr], domain);
		if ((he = gethostbyname(pool)) != NULL) {
			if (*((int *)he->h_addr) == last_addr)
				dups++;
			last_addr = *((int *)he->h_addr);
		} else {
			printf("error resolving %s\n", pool);
		}
	}
	printf("dups: %zd\n", dups);

	return 0;
}
